config/routes.rb
Rails.application.routes.draw do
  # get "price_alerts/send_price_alert"
  get "home/index"
  get "pages/index"

  resources :products

  get "/storefronts/preview", to: "storefronts#preview" # has to be before next line
  resources :storefronts, except: [:destroy] do
    get :choose_template, on: :member
    get :customize, on: :member
  end

  resources :price_alerts, only: [:new, :create, :index, :edit, :update], param: :id do
    get :delete, on: :member
    delete :destroy, on: :member
  end

  get "/send_price_alert", to: "price_alerts#send_price_alert", as: "send_price_alert"

  get "/signup", to: "users#new", as: "signup"
  post "/signup", to: "users#create", as: "signup_submit"
  get "/register", to: "users#register", as: "register"
  post "/register", to: "users#new_seller", as: "seller"
  get "/purchase_history", to: "users#purchase_history", as: "purchase_history"
  get "/sales_history", to: "users#sales_history", as: "sales_history"

  get "/request_storefront", to: "storefronts#make_request"
  get "/process_request", to: "storefronts#process_request"
  get "/show_requests", to: "users#show_requests"
  get "/process_admin_review", to: "storefronts#process_admin_review"

  post "/add_to_cart", to: "carts#add_to_cart", as: "add_to_cart"

  get "/checkout", to: "checkouts#index", as: "checkout"
  post "/update_quantity", to: "checkouts#update_quantity", as: "update_quantity"
  delete "/remove_item", to: "checkouts#remove_from_cart", as: "remove_item"
  post "/pay", to: "checkouts#update_product_inventory", as: "update_product_inventory"
  get "/forgot_password", to: "forgot_password#new", as: "forgot_password"
  post "/forgot_password_send_link", to: "forgot_password#send_link", as: "forgot_password_submit"
  get "/forgot_password_reset_password", to: "forgot_password#edit", as: "forgot_password_reset"
  post "/forgot_password_reset_password_submit", to: "forgot_password#update", as: "forgot_password_reset_submit"
  get "/review", to: "reviews#new", as: "review"
  post "/create_review", to: "reviews#create", as: "create_review"
  get "/reviews", to: "reviews#index", as: "reviews"
  get "/auth/:provider/callback", to: "sessions#omniauth"
  get "/send_message", to: "messages#new", as: "send_message"
  post "/send_message_submit", to: "messages#create", as: "send_message_submit"
  get "/view_messages", to: "messages#inbox", as: "view_messages"
  get "/view_sent_messages", to: "messages#sent", as: "view_sent_messages"
  get "/show_message", to: "messages#show", as: "message_details"
  get "/reply", to: "messages#reply", as: "reply"
  post "/send_reply", to: "messages#create_reply", as: "send_reply"
  delete "/delete_message", to: "messages#delete", as: "delete_message"

  get "/history", to: "products#history", as: "products_history"

  resources :profiles, only: [:show, :new, :create, :edit, :update], param: :id do
    get :delete, on: :member
    delete :destroy, on: :member
  end

  resources :promotions, except: [:index, :destroy]

  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create", as: "login_submit"
  get "/logout", to: "sessions#destroy", as: "logout"
  get "/shop", to: "products#index", as: "shop"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "home#index"

  # Defines routes for our custom error pages.
  # to: "controller#action" specifies the controller and action.
  # via: :all uses the same route for all HTTP methods (GET, POST, etc).
  match "/404", to: "errors#not_found", via: :all, as: :not_found
  match "/500", to: "errors#internal_server_error", via: :all, as: :internal_server_error
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"

  validates :sender_id, presence: true
  validates :sender_name, presence: true
  validates :receiver_name, presence: true
  validates :receiver_id, presence: true
  validates :message, presence: true, length: {maximum: 500}
  validates :subject, presence: true, length: {maximum: 100}
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_login

  def new
    @message = Message.new

    @profile_id = params[:profile_id]
    @profile = Profile.find @profile_id
    @receiver_id = @profile.user_id
    @name = @profile.user.full_name

    if Current.user.id == @receiver_id.to_i
      flash[:alert] = "You cannot send a message to yourself."
      p_id = Profile.find_by(user_id: Current.user.id).id
      redirect_to profile_path(p_id)
    end
  end

  def reply
    @message = Message.new

    @message_replying_to = params[:message]
    @subject_replying_to = params[:subject]
    @receiver_name = params[:sender_name]
    @receiver_id = params[:sender_id]
  end

  def create_reply
    sender_name = Current.user.full_name
    receiver_name = User.find_by(id: params[:receiver_id]).full_name
    message = Message.new(receiver_id: params[:receiver_id], sender_id: Current.user.id, subject: params[:message][:subject], message: params[:message][:message], sender_name: sender_name, receiver_name: receiver_name)
    if message.save
      flash[:success] = "Reply successfully sent!"
      redirect_to view_messages_path
    else
      render "reply", status: :unprocessable_entity
    end
  end

  def create
    sender_name = Current.user.full_name
    receiver_name = User.find_by(id: params[:receiver_id]).full_name
    message = Message.new(receiver_id: params[:receiver_id], sender_id: Current.user.id, subject: params[:message][:subject], message: params[:message][:message], sender_name: sender_name, receiver_name: receiver_name)
    if message.save
      flash[:success] = "Message successfully sent!"
      redirect_to profile_path(params[:profile_id])
    else
      render "new", status: :unprocessable_entity
    end
  end

  def inbox
    # only grab non deleted messages
    @messages = Message.where(receiver_id: Current.user.id, hasReceiverDeleted: false).order(created_at: :desc)
  end

  def sent
    @messages = Message.where(sender_id: Current.user.id, hasSenderDeleted: false).order(created_at: :desc)
  end

  def show
    @message = Message.find_by(id: params[:message_id])
    if Current.user.id == @message.sender_id # only time a message is read is when the reciever opens it
      @reply_enabled = false
      @message.update(hasRead: false)
    else
      @reply_enabled = true
      @message.update(hasRead: true)
    end
  end

  def delete
    if params[:confirmation] == "yes"
      flash[:success] = "Message deleted."
      message = Message.find_by(id: params[:message_id])
      if Current.user.id == message.sender_id
        message.update(hasSenderDeleted: true)
        redirect_to view_sent_messages_path
      else
        message.update(hasReceiverDeleted: true)
        redirect_to view_messages_path
      end
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_delete.html.erb
<div class="modal fade" id="confirmationModal" tabindex="-1" role="dialog" aria-labelledby="confirmationModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="confirmationModalLabel">Confirm Deletion</h5>
      </div>
      <div class="modal-body">
        Are you sure you want to delete this message?
      </div>
      <div class="modal-footer">
        <%= bootstrap_form_with url: delete_message_path, method: :delete, id: "confirmDeleteForm" do |f| %>
          <%= f.hidden_field(
                :message_id,
                id: "messageIdPlaceholder",
                data: { messages_target: "hiddenMessageField" }
              ) %>
          <%= f.hidden_field :confirmation, value: "yes" %>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" aria-label="Close">Close</button>
          <%= f.submit "Delete", class: "btn btn-danger" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/messages/inbox.html.erb
<div data-controller="messages">

<div class="container mt-4">
  <h2>Messages</h2>
  <%=  link_to "Inbox", view_messages_path, class: "btn btn-primary"%>
  <%=  link_to "Sent", view_sent_messages_path, class: "btn btn-primary"%>
  <table class="table">
    <thead>
    <tr>
      <th></th>
      <th>From</th>
      <th>Subject</th>
      <th>Message</th>
      <th>Date</th>
      <th></th>
      <th></th>

    </tr>
    </thead>
    <tbody>
    <% @messages.each do |message| %>
      <tr class="<%= message[:hasRead] ? 'table-light' : 'table-primary' %>">
        <td>
          <%= message[:hasRead] ? icon("opened-envelope", aria_label: "Opened Envelope") : icon("closed-envelope", aria_label: "Closed Envelope") %>
        </td>
        <td><%= message[:sender_name] %></td>
        <td>
          <%= truncate(message[:subject], length: 20) %>
        </td>
        <td>
          <%= truncate(message[:message], length: 20) %>
        </td>
        <td>
          <%= message[:created_at].strftime("%B %e, %Y %l:%M %p") %>
        </td>
        <td>
          <%= link_to "View Details", message_details_path(message_id: message[:id]), method: :get, class: "btn btn-primary" %>
        </td>
        <td>
          <button class="btn btn-danger delete-message"
                  data-action="messages#updateDeleteModal"
                  type="button"
                  data-messages-message-id-param="<%= message[:id] %>"
                  data-bs-toggle="modal"
                  data-bs-target="#confirmationModal">
            <%= icon("trash-can", aria_label: "Trash Can") %>
          </button>
        </td>
      </tr>
    <% end %>
    </tbody>

  </table>
</div>
  <%= render 'delete' %>
</div>

app/views/messages/new.html.erb
<div class="row d-flex justify-content-center align-items-center">
  <div class="col-sm-12 col-md-10 col-lg-8">
    <div class="card p-5">
      <h1 class="text-center mb-3">Send a Message</h1>
      <p class="text-center mb-3"><em>
        <% unless @name.blank? %>
          <%=  "You are messaging: #{@name}"  %>
        <%  end %>
      </em></p>
      <%= bootstrap_form_with model: @message, url: send_message_submit_path do |f| %>
        <%= hidden_field_tag :receiver_id, @receiver_id %>
        <%= hidden_field_tag :profile_id, @profile_id %>

        <%= f.text_field :subject, label: "Subject", placeholder: "Subject", maxlength: 100 %>
        <%= f.text_area :message, label: "Body", placeholder: "Body", style: "height: 20em;", maxlength: 500 %>


        <%= link_to "Cancel", :back, class: "btn btn-secondary" %>
        <%= f.submit "Send", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/messages/reply.html.erb
<div class="row d-flex justify-content-center align-items-center">
  <div class="col-sm-12 col-md-10 col-lg-8">
    <div class="card p-5">
      <h1 class="text-center mb-3">Send a Reply</h1>
      <p class="text-center mb-3"><em>
          <%=  "You are replying to: #{@receiver_name}"  %>
      </em></p>
      <br>
      <%= bootstrap_form_with model: @message, url: send_reply_path do |f| %>
        <%= hidden_field_tag :receiver_id, @receiver_id %>
        <%= f.text_field :subject, label: "Subject", placeholder: "Subject", maxlength: 100 %>
        <% original_message_lines = @message_replying_to.split("\n").map { |line| "> #{line}" } %>
        <%= f.text_area :message, label: "Body", placeholder: "Body", style: "height: 20em;", maxlength: 500, value: original_message_lines.join("\n").strip %>
        <%= link_to "Cancel", :back, class: "btn btn-secondary" %>
        <%= f.submit "Send", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/messages/sent.html.erb
<div data-controller="messages">

  <div class="container mt-4">
    <h2>Messages</h2>
    <%=  link_to "Inbox", view_messages_path, class: "btn btn-primary"%>
    <%=  link_to "Sent", view_sent_messages_path, class: "btn btn-primary"%>

    <table class="table">
      <thead>
      <tr>
        <th>To</th>
        <th>Subject</th>
        <th>Message</th>
        <th>Date</th>
        <th></th>
        <th></th>

      </tr>
      </thead>
      <tbody>
      <% @messages.each do |message| %>
      <tr>
          <td><%= message[:receiver_name] %></td>
          <td>
            <%= truncate(message[:subject], length: 20) %>
          </td>
          <td>
            <%= truncate(message[:message], length: 20) %>
          </td>
          <td>
            <%= message[:created_at].strftime("%B %e, %Y %l:%M %p") %>
          </td>
          <td>
            <%= link_to "View Details", message_details_path(message_id: message[:id]), method: :get, class: "btn btn-primary" %>
          </td>
        <td>
          <button class="btn btn-danger delete-message"
                  data-action="messages#updateDeleteModal"
                  type="button"
                  data-messages-message-id-param="<%= message[:id] %>"
                  data-bs-toggle="modal"
                  data-bs-target="#confirmationModal">
            <%= icon("trash-can", aria_label: "Trash Can") %>
          </button>
        </td>
        </tr>
      <% end %>
      </tbody>

    </table>
  </div>
  <%= render 'delete' %>

</div>

app/views/messages/show.html.erb
<h1>Message Details</h1>
  <p><strong>From:</strong> <%= @message.sender_name %></p>
  <p style="word-wrap: break-word; max-width: 100%;"><strong>Subject:</strong> <%= @message.subject %></p>
  <p style="word-wrap: break-word; max-width: 100%;">
    <strong>Message:</strong>
    <% @message.message.split("\n").each do |line| %>
    <div><%= line %></div>
  <% end %>
  </p>
<%= form_tag reply_path, method: :get do %>
  <%= hidden_field_tag :message, @message.message %>
  <%= hidden_field_tag :subject, @message.subject %>
  <%= hidden_field_tag :sender_name, @message.sender_name %>
  <%= hidden_field_tag :sender_id, @message.sender_id %>
  <%= link_to "Back", :back, class: "btn btn-secondary" %>
  <% if @reply_enabled %>
    <%= submit_tag "Reply", class: "btn btn-primary" %>
  <% end %>
<% end %>
<br>