config/routes.rb
Rails.application.routes.draw do
  # get "price_alerts/send_price_alert"
  get "home/index"
  get "pages/index"

  resources :products

  get "/storefronts/preview", to: "storefronts#preview" # has to be before next line
  resources :storefronts, except: [:destroy] do
    get :choose_template, on: :member
    get :customize, on: :member
  end

  resources :price_alerts, only: [:new, :create, :index, :edit, :update], param: :id do
    get :delete, on: :member
    delete :destroy, on: :member
  end

  get "/send_price_alert", to: "price_alerts#send_price_alert", as: "send_price_alert"

  get "/signup", to: "users#new", as: "signup"
  post "/signup", to: "users#create", as: "signup_submit"
  get "/register", to: "users#register", as: "register"
  post "/register", to: "users#new_seller", as: "seller"
  get "/purchase_history", to: "users#purchase_history", as: "purchase_history"
  get "/sales_history", to: "users#sales_history", as: "sales_history"

  get "/request_storefront", to: "storefronts#make_request"
  get "/process_request", to: "storefronts#process_request"
  get "/show_requests", to: "users#show_requests"
  get "/process_admin_review", to: "storefronts#process_admin_review"

  post "/add_to_cart", to: "carts#add_to_cart", as: "add_to_cart"

  get "/checkout", to: "checkouts#index", as: "checkout"
  post "/update_quantity", to: "checkouts#update_quantity", as: "update_quantity"
  delete "/remove_item", to: "checkouts#remove_from_cart", as: "remove_item"
  post "/pay", to: "checkouts#update_product_inventory", as: "update_product_inventory"
  get "/forgot_password", to: "forgot_password#new", as: "forgot_password"
  post "/forgot_password_send_link", to: "forgot_password#send_link", as: "forgot_password_submit"
  get "/forgot_password_reset_password", to: "forgot_password#edit", as: "forgot_password_reset"
  post "/forgot_password_reset_password_submit", to: "forgot_password#update", as: "forgot_password_reset_submit"
  get "/review", to: "reviews#new", as: "review"
  post "/create_review", to: "reviews#create", as: "create_review"
  get "/reviews", to: "reviews#index", as: "reviews"
  get "/auth/:provider/callback", to: "sessions#omniauth"
  get "/send_message", to: "messages#new", as: "send_message"
  post "/send_message_submit", to: "messages#create", as: "send_message_submit"
  get "/view_messages", to: "messages#inbox", as: "view_messages"
  get "/view_sent_messages", to: "messages#sent", as: "view_sent_messages"
  get "/show_message", to: "messages#show", as: "message_details"
  get "/reply", to: "messages#reply", as: "reply"
  post "/send_reply", to: "messages#create_reply", as: "send_reply"
  delete "/delete_message", to: "messages#delete", as: "delete_message"

  get "/history", to: "products#history", as: "products_history"

  resources :profiles, only: [:show, :new, :create, :edit, :update], param: :id do
    get :delete, on: :member
    delete :destroy, on: :member
  end

  resources :promotions, except: [:index, :destroy]

  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create", as: "login_submit"
  get "/logout", to: "sessions#destroy", as: "logout"
  get "/shop", to: "products#index", as: "shop"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "home#index"

  # Defines routes for our custom error pages.
  # to: "controller#action" specifies the controller and action.
  # via: :all uses the same route for all HTTP methods (GET, POST, etc).
  match "/404", to: "errors#not_found", via: :all, as: :not_found
  match "/500", to: "errors#internal_server_error", via: :all, as: :internal_server_error
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :session_token
  has_secure_password
  before_save { |user| user.email = user.email.downcase }
  before_save :create_session_token
  # If a user's is_seller attribute is changed to true, make sure they have a profile.
  # This has to be after a commit because (for new users) we need to save the user
  # before we can create a profile for them.
  after_save_commit :update_profile_visibility,
    if: [:saved_change_to_is_seller?, :is_seller?]

  validates :first_name, presence: true, length: {maximum: 50}
  validates :last_name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,24})\z/i
  validates :email, presence: true,
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
  # allow_nil allows us to update a user without changing their password. Note that
  # this doesn't allow us to create a user without a password, since has_secure_password
  # requires a password on creation. See https://stackoverflow.com/a/45329148
  validates :password, presence: true, length: {minimum: 8}, allow_nil: true
  validates :password_confirmation, presence: true, length: {minimum: 8}, on: :create
  validate :password_is_secure

  def password_is_secure
    unless /[A-Z]/.match?(password)
      errors.add(:password, "must contain at least one capital letter")
    end
    unless /[!@#$%^&*(),.?":{}|<>]/.match?(password)
      errors.add(:password, "must contain at least one special character")
    end
    unless /[0-9]/.match?(password)
      errors.add(:password, "must contain at least one number")
    end
  end

  # Scopes allow us to write things like User.admins to get all admins
  # or User.non_sellers to get all users who aren't sellers.
  scope :admins, -> { where(is_admin: true) }
  scope :non_admins, -> { where(is_admin: false) }
  scope :sellers, -> { where(is_seller: true) }
  scope :non_sellers, -> { where(is_seller: false) }
  scope :buyers, -> { where(is_buyer: true) }
  scope :non_buyers, -> { where(is_buyer: false) }

  has_many :products, foreign_key: :seller_id, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_one :cart, dependent: :destroy
  has_many :cart_items, through: :cart
  has_many :reviews_user_has_given, class_name: "Review", foreign_key: :reviewer_id, dependent: :destroy
  has_many :reviews_for_sellers, class_name: "Review", foreign_key: :seller_id, dependent: :destroy
  has_many :cart_products, through: :carts, source: :product
  has_many :viewed_products
  has_many :viewed, through: :viewed_products, source: :product
  accepts_nested_attributes_for :profile  # If you want to handle profile attributes in user forms
  has_one :storefront, dependent: :destroy
  accepts_nested_attributes_for :storefront
  has_many :promotions, foreign_key: :seller_id, dependent: :destroy
  has_many :messages_sent, class_name: "Message", foreign_key: :sender_id, dependent: :destroy
  has_many :messages_received, class_name: "Message", foreign_key: :receiver_id, dependent: :destroy
  has_many :price_alerts, dependent: :destroy

  # Override the is_admin setter so that all admins are sellers and buyers.
  def is_admin=(value)
    super(value)
    self.is_seller ||= value
    self.is_buyer ||= value
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  private

  def create_session_token
    self.session_token = SecureRandom.urlsafe_base64
  end

  def update_profile_visibility
    if is_seller? && (profile.nil? || !profile.public_profile)
      build_profile(public_profile: true) unless profile
      profile.update(public_profile: true)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:register, :new_seller]
  before_action :require_not_seller, only: [:register, :new_seller]

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def index
  end

  def show
    @user = Current.user
    unless Current.user?(params[:id])
      flash[:warning] = "Can only show profile of logged-in user"
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Sign up successful!"
      redirect_to login_path
    else
      flash[:alert] = "Invalid input(s)!"
      render "new", status: :unprocessable_entity
    end
  end

  def purchase_history
    if session[:user_id].nil?
      flash[:alert] = "You must log in to view your purchase history"
      redirect_to login_path
    else
      @user = Current.user
      @others = []
      @transactions = Transaction.where(buyer_id: @user.id).order(created_at: :desc)
      @transactions.each do |t|
        sid = t.seller_id
        @seller = User.where(id: sid).first
        @product = Product.where(id: t.product_id).first
        if @seller.storefront.nil?
          @others.append({seller: @seller.first_name + " " + @seller.last_name, storefront: @seller.storefront, profile: @seller.profile, product: @product.name, quantity: t.quantity, price_cents: t.price_cents.to_f / 100.0, created_at: t.created_at, product_id: @product.id})
        else
          sf = Storefront.where(user_id: @seller.id).first
          @others.append({seller: sf.name, storefront: @seller.storefront, profile: @seller.profile, product: @product.name, quantity: t.quantity, price_cents: t.price_cents.to_f / 100.0, created_at: t.created_at, product_id: @product.id})
        end
      end
    end
  end

  def sales_history
    if session[:user_id].nil?
      flash[:alert] = "You must log in to view your sales history"
    elsif Current.user.is_seller
      @user = Current.user
      @others = []
      @transactions = Transaction.where(seller_id: @user.id).order(created_at: :desc)
      @transactions.each do |t|
        bid = t.buyer_id
        @buyer = User.where(id: bid).first
        @product = Product.where(id: t.product_id).first
        @others.append({buyer: @buyer.first_name + " " + @buyer.last_name, product: @product.name, quantity: t.quantity, profile: @buyer.profile, price_cents: t.price_cents.to_f / 100.0, created_at: t.created_at, product_id: @product.id})
      end
    else
      flash[:alert] = "You must register as a seller to view sales history"
      redirect_to root_path
    end
  end

  def register
  end

  def new_seller
    Current.user.update_attribute(:is_seller, true)
    Current.user.update_attribute(:storefront_requested, 0)
    flash[:notice] = "Registration successful"
    redirect_to root_path
  end

  def show_requests
    if Current.user.nil?
      flash[:alert] = "Please log in."
      redirect_to login_path and return
    end
    unless Current.user.is_admin?
      flash[:alert] = "You do not have permission to view that page."
      redirect_to root_path and return
    end
    @reqs = []
    User.where(storefront_requested: 100).each do |user|
      puts user
      @reqs.append({user: user})
    end
  end
end

app/views/users/new.html.erb
<div class="row d-flex justify-content-center align-items-center">
  <div class="col-sm-10 col-md-7 col-lg-6">
    <div class="card p-5">
      <h1 class="text-center mb-3">Signup</h1>
      <%= bootstrap_form_with model: @user, url: signup_submit_path, method: :post, local: true, class: "px-3 py-1" do |f| %>
        <div class="row">
          <div class="col-md-6">
            <%= f.text_field :first_name, label: "First Name", placeholder: "First Name" %>
          </div>
          <div class="col-md-6">
            <%= f.text_field :last_name, label: "Last Name", placeholder: "Last Name" %>
          </div>
        </div>
        <%= f.email_field :email, label: "Email", placeholder: "Email" %>
        <%= f.password_field :password, label: "Password", placeholder: "Password", help: "Must be at least 8 characters long<br>Must contain at least one capital letter<br>Must contain at least one special character<br>Must contain at least one number".html_safe  %>

        <%= f.password_field :password_confirmation, label: "Confirm Password", placeholder: "Confirm Password" %>
        <div class="d-flex justify-content-center mt-4">
          <%= f.submit "Signup", extra_class: "btn-lg w-75" %>
        </div>
        <div class="d-flex justify-content-center mt-3">
          <span>Already have an account? <%= link_to "Login", login_path, id: "login-link" %></span>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/purchase_history.html.erb
<div class="container mt-4">
  <h2> Purchase history for <%= @user.first_name %></h2>
  <table class="table">
    <thead>
    <tr>
      <%# link_to defaults to the current URL when none is specified %>
      <th scope="col"> Seller </th>
      <th scope="col"> Item </th>
      <th scope="col"> Price</th>
      <th scope="col"> Quantity </th>
      <th scope="col"> Total </th>
      <th scope="col"> Purchased on </th>
    </tr>
    </thead>
    <tbody>
    <% @others.each do |m| %>
      <tr>
        <td>
          <%= if m[:storefront].nil?
                link_to m[:seller], profile_path(m[:profile])
        else
          link_to m[:seller], storefront_path(m[:storefront])
        end%></td>
        <td> <%= link_to m[:product], product_path(m[:product_id]) %></td>
        <td><%= number_to_currency m[:price_cents] %></td>
        <td><%= m[:quantity] %></td>
        <td><%= number_to_currency(m[:price_cents] * m[:quantity]) %></td>
        <td><%= m[:created_at].strftime("%B %e, %Y %l:%M %p") %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/users/register.html.erb
<div class="row d-flex justify-content-center align-items-center">
  <div class="col-sm-12 col-md-10 col-lg-8">
    <div class="card p-5">
      <h2 class="text-center mb-3">Register to sell</h2>
      <p>
        To sell items on the marketplace, you must fill out the form below.
        Sellers are
        <span class="fw-bold">required</span>
        to have a public profile:
      </p>
      <ul>
        <li>
          If you don't have a profile, a public one will be created for you
          automatically.
        </li>
        <li>
          If you do have one, it will be made public if it isn't already.
        </li>
      </ul>
      <p class="mb-5">
        Once you register, your profile cannot be made private. Along with this,
        <strong class="text-danger">
          you will not be able to delete your account.
        </strong>
      </p>
      <%= bootstrap_form_with model: @user, url: register_path do |f| %>
        <%= f.check_box(
              :understand_above,
              required: true,
              label: "I understand the above and wish to register"
            ) %>
        <%= f.check_box(
              :agree_tos,
              required: true,
              label: "I have read and agree to the #{
                  future_link_to "terms and conditions"
                }".html_safe
            ) %>
        <div class="d-flex justify-content-center mt-4">
          <%= f.submit "Register", extra_class: "w-25" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/sales_history.html.erb
<div class="container mt-4">
  <h2> Sales history for <%= @user.first_name %></h2>
  <table class="table">
    <thead>
    <tr>
      <%# link_to defaults to the current URL when none is specified %>
      <th scope="col"> Item </th>
      <th scope="col"> Price </th>
      <th scope="col"> Sold to </th>
      <th scope="col"> Sold on </th>
    </tr>
    </thead>
    <tbody>
    <% @others.each do |m| %>
      <tr>
        <td> <%= link_to m[:product], product_path(m[:product_id]) %></td>
        <td><%= number_to_currency m[:price_cents] %></td>
       <td>
          <% if !@buyer.profile.nil? %>
            <%= link_to m[:buyer], profile_path(@buyer.profile.id) %>
          <% else %>
            <%= @buyer.full_name %>
          <% end %>
        </td>
        <td><%= m[:created_at].strftime("%B %e, %Y %l:%M %p") %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/users/show_requests.html.erb
<div class="container mt-4">
  <h2>Pending storefront requests</h2>
  <table class="table">
    <thead>
    <tr>
      <%# link_to defaults to the current URL when none is specified %>
      <th>Name</th>
      <th> </th>
      <th> </th>
      <th> </th>
    </tr>
    </thead>
    <tbody>
    <% @reqs.each do |r| %>
      <% user = r[:user] %>
      <tr>
        <td><%= link_to user.first_name + " " + user.last_name, profile_path(user.profile) %></td>
        <td><%= link_to "Approve", process_admin_review_path(approve: "true", user: user.id), class: "btn btn-primary"%></td>
        <td><%= link_to "Reject", process_admin_review_path(approve: "false", user: user.id), class: "btn btn-danger"%></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/users/transaction_history.html.erb
<div class="container mt-4">
  <h2><%= if @user.is_seller
            "Sales"
          else
            "Purchase"
  end%> history for <%= @user.first_name %></h2>
  <table class="table">
    <thead>
    <tr>
      <%# link_to defaults to the current URL when none is specified %>
      <th scope="col"> Seller </th>
      <th scope="col"> Name </th>
      <th scope="col"> Price</th>
      <th scope="col"> Purchased on </th>
    </tr>
    </thead>
    <tbody>
    <% @others.each do |m| %>
      <tr>
        <td> <%= if @seller.storefront.nil?
                   @seller.first_name + " " + @seller.last_name
        else
          link_to @seller.first_name + " " + @seller.last_name, storefront_path(@seller.storefront)
        end%></td>
        <td> <%= link_to m[:product], product_path(m[:product_id]) %></td>
        <td><%= number_to_currency m[:price] %></td>
        <td><%= m[:created_at] %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>