config/routes.rb
Rails.application.routes.draw do
  # get "price_alerts/send_price_alert"
  get "home/index"
  get "pages/index"

  resources :products

  get "/storefronts/preview", to: "storefronts#preview" # has to be before next line
  resources :storefronts, except: [:destroy] do
    get :choose_template, on: :member
    get :customize, on: :member
  end

  resources :price_alerts, only: [:new, :create, :index, :edit, :update], param: :id do
    get :delete, on: :member
    delete :destroy, on: :member
  end

  get "/send_price_alert", to: "price_alerts#send_price_alert", as: "send_price_alert"

  get "/signup", to: "users#new", as: "signup"
  post "/signup", to: "users#create", as: "signup_submit"
  get "/register", to: "users#register", as: "register"
  post "/register", to: "users#new_seller", as: "seller"
  get "/purchase_history", to: "users#purchase_history", as: "purchase_history"
  get "/sales_history", to: "users#sales_history", as: "sales_history"

  get "/request_storefront", to: "storefronts#make_request"
  get "/process_request", to: "storefronts#process_request"
  get "/show_requests", to: "users#show_requests"
  get "/process_admin_review", to: "storefronts#process_admin_review"

  post "/add_to_cart", to: "carts#add_to_cart", as: "add_to_cart"

  get "/checkout", to: "checkouts#index", as: "checkout"
  post "/update_quantity", to: "checkouts#update_quantity", as: "update_quantity"
  delete "/remove_item", to: "checkouts#remove_from_cart", as: "remove_item"
  post "/pay", to: "checkouts#update_product_inventory", as: "update_product_inventory"
  get "/forgot_password", to: "forgot_password#new", as: "forgot_password"
  post "/forgot_password_send_link", to: "forgot_password#send_link", as: "forgot_password_submit"
  get "/forgot_password_reset_password", to: "forgot_password#edit", as: "forgot_password_reset"
  post "/forgot_password_reset_password_submit", to: "forgot_password#update", as: "forgot_password_reset_submit"
  get "/review", to: "reviews#new", as: "review"
  post "/create_review", to: "reviews#create", as: "create_review"
  get "/reviews", to: "reviews#index", as: "reviews"
  get "/auth/:provider/callback", to: "sessions#omniauth"
  get "/send_message", to: "messages#new", as: "send_message"
  post "/send_message_submit", to: "messages#create", as: "send_message_submit"
  get "/view_messages", to: "messages#inbox", as: "view_messages"
  get "/view_sent_messages", to: "messages#sent", as: "view_sent_messages"
  get "/show_message", to: "messages#show", as: "message_details"
  get "/reply", to: "messages#reply", as: "reply"
  post "/send_reply", to: "messages#create_reply", as: "send_reply"
  delete "/delete_message", to: "messages#delete", as: "delete_message"

  get "/history", to: "products#history", as: "products_history"

  resources :profiles, only: [:show, :new, :create, :edit, :update], param: :id do
    get :delete, on: :member
    delete :destroy, on: :member
  end

  resources :promotions, except: [:index, :destroy]

  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create", as: "login_submit"
  get "/logout", to: "sessions#destroy", as: "logout"
  get "/shop", to: "products#index", as: "shop"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "home#index"

  # Defines routes for our custom error pages.
  # to: "controller#action" specifies the controller and action.
  # via: :all uses the same route for all HTTP methods (GET, POST, etc).
  match "/404", to: "errors#not_found", via: :all, as: :not_found
  match "/500", to: "errors#internal_server_error", via: :all, as: :internal_server_error
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :set_current_user

  def set_current_user
    Current.user = User.find_by(id: session[:user_id])
  end

  protected

  # Returns the translation for the current controller and action being processed.
  # Translations are located in the `config/locales` directory.
  #
  # A scope can be passed in to request a translation under a different namespace.
  # Default keys for the controller name are also searched if the key isn't found.
  #
  # For example, if the request is `GET profiles/1/edit` and the scope is
  # :require_login, the following translations will be checked (in order):
  #
  # * require_login.profiles.edit
  # * require_login.profiles.default
  # * require_login.default
  #
  # If none of those keys are found, nil will be returned.
  #
  # * action: the action name
  # * controller: the controller name
  #
  # This can be useful to customize the default translation for a specific action
  # or controller.
  #
  # @param scope [String, Symbol] The scope to use for the translation.
  # @param options [Hash] Additional options to pass to the translation method.
  # @return [String] The translated string.
  def i18n_t(scope: nil, **options)
    key = "#{controller_name}.#{action_name}"
    I18n.translate key,
      scope: scope,
      # Use symbols for defaults so that they're treated as keys;
      # strings are treated as values so won't be looked up
      default: [:"#{controller_name}.default", :default],
      # pass in the action and controller names as interpolations
      # in case defaults want to use them
      action: action_name,
      controller: controller_name,
      **options
  end

  # Redirects to the login page if the user is not logged in.
  # An :alert flash is set before redirecting, using the translation for
  # the requested controller and action under the :require_login scope.
  # See #i18n_t.
  def require_login
    unless Current.user
      flash[:alert] = i18n_t scope: :require_login
      redirect_to login_path
    end
  end

  # Redirects to the root path if the current user is not a seller.
  # An :alert flash is set before redirecting, using the translation for
  # the requested controller and action under the :require_seller scope.
  # See #i18n_t.
  def require_seller
    unless Current.user&.is_seller || Current.user&.is_admin
      flash[:alert] = i18n_t scope: :require_seller
      redirect_to root_path
    end
  end

  # Redirects to the root path if the current user is a seller.
  # An :alert flash is set before redirecting, using the translation for
  # the requested controller and action under the :require_not_seller scope.
  # See #i18n_t.
  def require_not_seller
    if Current.user&.is_seller
      flash[:alert] = i18n_t scope: :require_not_seller
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/navbar_helper.rb
module NavbarHelper
  # <li class="nav-item">...</li>
  def navbar_item(**options, &block)
    options[:class] = class_names "nav-item", options[:class]
    # <li class="nav-item">...</li>
    tag.li(**options, &block)
  end

  # Creates a navbar link.
  # If the current page is the linked page, the link is given the active class. This
  # can be overridden by passing the :active option.
  #
  # <code>
  # <li class="nav-item">
  #     <a class="nav-link" href="#{path}">#{text}</a>
  # </li>
  # </code>
  #
  # @param [Array] args If a block is given, the argument is the path. Otherwise, the
  #   arguments are the text and the path.
  # @param [Hash] options The options to pass to the link_to helper.
  # @option options [Hash] :li_options The options to pass to the navbar_item helper.
  # @option options [Boolean] :active Whether or not the link is active.
  # @option options [Boolean] :disabled Whether or not the link is disabled.
  # @yieldreturn [String] If given, the block is used as the link text.
  # @return [String] The HTML for the navbar link.
  def navbar_link(*args, **options, &block)
    path = block ? args[0] : args[1]

    li_options = options.delete(:li_options) || {}

    active = options.delete(:active) { current_page?(path) } && "active"
    disabled = options.delete(:disabled) && "disabled"
    options[:aria] = {current: "page"}.merge(options[:aria] || {}) if active
    options[:class] = class_names "nav-link", active, disabled, options[:class]

    link = if options.delete(:future_link)
      future_link_to(*args, **options, &block)
    else
      link_to(*args, **options, &block)
    end

    navbar_item(**li_options) { link }
  end

  # Creates a navbar dropdown.
  # <li class="nav-item dropdown">
  #     <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">#{text}</a>
  #     <ul class="dropdown-menu">...</ul>
  # </li>
  def navbar_dropdown(text, **options, &block)
    li_options = options.delete(:li_options) || {}
    li_options[:class] = class_names "dropdown", li_options[:class]
    ul_options = options.delete(:ul_options) || {}
    ul_options[:class] = class_names "dropdown-menu", ul_options[:class]

    options = options.delete(:options) || {}
    options[:role] = "button"
    options[:class] = class_names "nav-link", "dropdown-toggle", options[:class]
    options[:data] = {bs_toggle: "dropdown"}.merge(options[:data] || {})
    options[:aria] = {expanded: "false"}.merge(options[:aria] || {})

    navbar_item(**li_options) do
      out = []
      out << link_to(text, "#", **options)
      out << tag.ul(**ul_options, &block)
      safe_join out
    end
  end

  # Creates a navbar dropdown link.
  # <li><a class="dropdown-item" href="#{path}">#{text}</a></li>
  def dropdown_link(text, path, **options)
    li_options = options.delete(:li_options) || {}
    options[:class] = class_names "dropdown-item", options[:class]
    tag.li(**li_options) { link_to(text, path, **options) }
  end

  def dropdown_divider(**options)
    li_options = options.delete(:li_options) || {}
    options[:class] = class_names "dropdown-divider", options[:class]
    tag.li(**li_options) { tag.hr(**options) }
  end

  def user_button(**options)
    if Current.user
      render "application/navbar/user_dropdown", user: Current.user, options: options
    else
      navbar_link("Login", login_path, **options)
    end
  end
end

app/views/application/navbar/_search_bar.html.erb
<div data-controller="search-bar">
  <%# The action attribute gets set by JavaScript when submit.
      See app/javascript/controllers/search_bar_controller.js %>
  <form class="d-flex"
        role="search"
        method="get"
        data-action="search-bar#search">
    <div class="input-group">
      <div class="input-group-addon">
        <select class="form-select search-bar-select"
                aria-label="Select type of item to search for"
                autocomplete="off"
                data-search-bar-target="path">
          <option <%= tag.attributes selected: current_page?(products_path),
                        value: products_path %>>
            Products
          </option>
          <option <%= tag.attributes selected: current_page?(storefronts_path),
                        value: storefronts_path %>>
            Storefronts
          </option>
        </select>
      </div>
      <input class="form-control me-2"
             type="search"
             name="search"
             placeholder="Search"
             aria-label="Search"
             autocomplete="off"
             value="<%= params[:search] || "" %>">
    </div>
  </form>
</div>

app/views/application/navbar/_user_dropdown.html.erb
<%= navbar_dropdown user.full_name, **options do %>
  <%= dropdown_link "Profile", user.profile ? profile_path(user.profile) : new_profile_path %>
  <%= dropdown_link "Messages", view_messages_path %>
  <% if user.is_seller %>
    <% if user.storefront&.id.present? %>
      <%= dropdown_link "Your Storefront", storefront_path(user.storefront.id) %>
      <%= dropdown_link "Edit Storefront", edit_storefront_path(user.storefront.id) %>
    <% else %>
      <% if user.storefront_requested == 400 %>
        <%= dropdown_link "Create Storefront", new_storefront_path %>
      <% else %>
        <%= dropdown_link "Request Storefront", request_storefront_path %>
      <% end %>
    <% end %>
    <%= dropdown_link "Post a product", new_product_path %>
    <%= dropdown_link "Sold items", sales_history_path %>
    <%= dropdown_link "Create a promotion", new_promotion_path %>
  <% else %>
    <%= dropdown_link "Register as seller", register_path %>
  <% end %>
  <% if user.is_admin %>
    <%= dropdown_link "Storefront Requests", show_requests_path %>
  <% end %>
  <%= dropdown_link "Price Alerts", price_alerts_path  %>
  <%= dropdown_link "Shopping history", products_history_path %>
  <%= dropdown_link "Purchase history", purchase_history_path %>
  <%= dropdown_divider %>
  <%= dropdown_link("Logout", logout_path, method: :delete) %>
<% end %>