config/routes.rb
Rails.application.routes.draw do
  # get "price_alerts/send_price_alert"
  get "home/index"
  get "pages/index"

  resources :products

  get "/storefronts/preview", to: "storefronts#preview" # has to be before next line
  resources :storefronts, except: [:destroy] do
    get :choose_template, on: :member
    get :customize, on: :member
  end

  resources :price_alerts, only: [:new, :create, :index, :edit, :update], param: :id do
    get :delete, on: :member
    delete :destroy, on: :member
  end

  get "/send_price_alert", to: "price_alerts#send_price_alert", as: "send_price_alert"

  get "/signup", to: "users#new", as: "signup"
  post "/signup", to: "users#create", as: "signup_submit"
  get "/register", to: "users#register", as: "register"
  post "/register", to: "users#new_seller", as: "seller"
  get "/purchase_history", to: "users#purchase_history", as: "purchase_history"
  get "/sales_history", to: "users#sales_history", as: "sales_history"

  get "/request_storefront", to: "storefronts#make_request"
  get "/process_request", to: "storefronts#process_request"
  get "/show_requests", to: "users#show_requests"
  get "/process_admin_review", to: "storefronts#process_admin_review"

  post "/add_to_cart", to: "carts#add_to_cart", as: "add_to_cart"

  get "/checkout", to: "checkouts#index", as: "checkout"
  post "/update_quantity", to: "checkouts#update_quantity", as: "update_quantity"
  delete "/remove_item", to: "checkouts#remove_from_cart", as: "remove_item"
  post "/pay", to: "checkouts#update_product_inventory", as: "update_product_inventory"
  get "/forgot_password", to: "forgot_password#new", as: "forgot_password"
  post "/forgot_password_send_link", to: "forgot_password#send_link", as: "forgot_password_submit"
  get "/forgot_password_reset_password", to: "forgot_password#edit", as: "forgot_password_reset"
  post "/forgot_password_reset_password_submit", to: "forgot_password#update", as: "forgot_password_reset_submit"
  get "/review", to: "reviews#new", as: "review"
  post "/create_review", to: "reviews#create", as: "create_review"
  get "/reviews", to: "reviews#index", as: "reviews"
  get "/auth/:provider/callback", to: "sessions#omniauth"
  get "/send_message", to: "messages#new", as: "send_message"
  post "/send_message_submit", to: "messages#create", as: "send_message_submit"
  get "/view_messages", to: "messages#inbox", as: "view_messages"
  get "/view_sent_messages", to: "messages#sent", as: "view_sent_messages"
  get "/show_message", to: "messages#show", as: "message_details"
  get "/reply", to: "messages#reply", as: "reply"
  post "/send_reply", to: "messages#create_reply", as: "send_reply"
  delete "/delete_message", to: "messages#delete", as: "delete_message"

  get "/history", to: "products#history", as: "products_history"

  resources :profiles, only: [:show, :new, :create, :edit, :update], param: :id do
    get :delete, on: :member
    delete :destroy, on: :member
  end

  resources :promotions, except: [:index, :destroy]

  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create", as: "login_submit"
  get "/logout", to: "sessions#destroy", as: "logout"
  get "/shop", to: "products#index", as: "shop"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "home#index"

  # Defines routes for our custom error pages.
  # to: "controller#action" specifies the controller and action.
  # via: :all uses the same route for all HTTP methods (GET, POST, etc).
  match "/404", to: "errors#not_found", via: :all, as: :not_found
  match "/500", to: "errors#internal_server_error", via: :all, as: :internal_server_error
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model

  REQUIRED_FIELDS = %i[name description price quantity condition].freeze

  belongs_to :seller, class_name: "User"
  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations
  has_many :cart_items
  has_and_belongs_to_many :promotions
  has_many :viewed_products
  has_many :viewed_by_users, through: :viewed_products, source: :user
  has_many :price_alerts, dependent: :destroy
  mount_uploaders :photos, ProductPhotoUploader

  # Left 100 between each value to allow for future additions.
  # Taken from https://www.recycledcycles.com/service/used-item-condition-guide/
  enum :condition,
    # DO NOT change these values.
    {poor: 0, fair: 100, good: 200, excellent: 300, new: 400},
    suffix: true,
    validate: true
  # monetize makes the price_cents attribute accessible as price and price=.
  # price is a Money object, which has a currency and a value.
  monetize :price_cents, numericality: {greater_than: 0}

  validates(*REQUIRED_FIELDS, presence: true) # parentheses required for splat operator
  validates :name, length: {maximum: 100}
  validates :description, length: {maximum: 1000}
  validates :quantity, numericality: {greater_than_or_equal_to: 0}
  validates :views, numericality: {greater_than_or_equal_to: 0}
  validates :private, inclusion: {in: [true, false]}

  scope :only_public, -> { where(private: false) }
  scope :only_private, -> { where(private: true) }
  scope :in_stock, -> { where("quantity > 0") }

  pg_search_scope :search_text,
    against: {name: "A", description: "B"},
    using: {
      tsearch: {
        dictionary: "english",
        tsvector_column: "searchable",
        prefix: true,
        any_word: true
      }
    }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :require_login, except: [:show, :index]
  before_action :require_seller, only: [:new, :create]

  def index
    @products = Product.includes(:categories).only_public.in_stock
    @products = @products.search_text(params[:search]) if params[:search]
    sort = params[:sort]
    unless %w[asc desc].include?(params[:order].to_s)
      redirect_to products_path(sort: params[:sort], search: params[:search], cat: params[:cat], order: "desc") and return
    end
    if sort
      # This is needed to clear the sort order imposed
      # by search_text (which orders by search rank).
      @products.order_values = []
      @products = case sort
      when "price"
        @products.order(price_cents: params[:order].to_sym)
      when "name"
        @products.order(name: params[:order].to_sym)
      when "date"
        @products.order(created_at: params[:order].to_sym)
      when "views"
        @products.order(views: params[:order].to_sym)
      else
        @products
      end
    end
    cat = params[:category]
    if cat
      if Category.where(id: cat).blank?
        flash[:alert] = "#{cat} isn't a valid category."
        redirect_to products_path(sort: params[:sort]) and return
      end
      @product = case sort
      when "price"
        Product.includes(:categories).only_public.in_stock.where(categories: cat).order(:price_cents)
      when "name"
        Product.includes(:categories).only_public.in_stock.where(categories: cat).order(:name)
      when "date"
        Product.includes(:categories).only_public.in_stock.where(categories: cat).order(created_at: :desc)
      when "views"
        Product.includes(:categories).only_public.in_stock.where(categories: cat).order(views: :asc)
      else
        Product.includes(:categories).only_public.in_stock.where(categories: cat).order(created_at: :desc)
      end
      @products = @products.joins(:categories).where(categories: {id: cat})
    end
    @products = @products.search_text(params[:search]) if params[:search]
  end

  def show
    # Raises ActiveRecord::RecordNotFound if not
    # found, which will render the 404 page.
    @product = Product.find params[:id]
    @seller = @product.seller
    @user = Current.user
    if @product.private
      unless Current.user == @seller || Current.user&.is_admin
        flash[:alert] = "You don't have permission to view that product."
        redirect_to root_path
      end
    end
    unless Current.user.nil?
      unless @product.viewed_by_users.include? Current.user
        @product.viewed_by_users << Current.user
        @product.update(views: @product.views + 1)
      end
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.seller = Current.user
    @product.views = 0
    if @product.save
      redirect_to @product
    else
      flash[:alert] = "Please fix the errors below."
      render "new", status: :unprocessable_entity
    end
  end

  def edit
    @product = Product.find params[:id]
    if Current.user != @product.seller && !Current.user.is_admin
      flash[:alert] = "You don't have permission to edit that product."
      redirect_to root_path
    end
  end

  def update
    @product = Product.find params[:id]
    old_price = @product.price
    if Current.user != @product.seller && !Current.user.is_admin
      flash[:alert] = "You don't have permission to edit that product."
      redirect_to root_path
    elsif @product.update(product_params)
      # if the price is now lower than any price alert thresholds, send an email
      @product.price_alerts.each do |price_alert|
        if @product.price.to_i < price_alert.threshold.to_i
          PriceAlertMailer.send_price_alert(price_alert.user.email, @product.id, price_alert.threshold, old_price).deliver_now
          price_alert.destroy
        end
      end
      redirect_to @product
    else
      flash[:alert] = "Please fix the errors below."
      render "edit", status: :unprocessable_entity
    end
  end

  def history
    if Current.user.nil?
      flash[:alert] = "Please log in to view your shopping history."
      redirect_to login_path
    else
      @user = Current.user
      ids = []
      @user.viewed_products.each do |vp|
        ids.append(vp.product_id)
      end
      @products = Product.where(id: ids)
      sort = params[:sort]
      @products = case sort
      when "price"
        @products.order(price_cents: params[:order].to_sym)
      when "name"
        @products.order(name: params[:order].to_sym)
      when "date"
        @products.order(created_at: params[:order].to_sym)
      when "views"
        @products.order(views: params[:order].to_sym)
      else
        @products
      end
    end
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :price,
      :quantity,
      :views,
      :condition,
      :private,
      {photos: []},
      category_ids: []
    )
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def products_index_header
    if params[:search].present?
      %(Search results for "#{params[:search]}")
    elsif params[:category].present?
      title = "Showing products in "
      Category.where(id: params[:category]).each do |c|
        title += c.name
      end
      title
    else
      "All Products for sale"
    end
  end
end

app/views/products/_form.html.erb
<%# multipart: true is needed since we're uploading files %>
<%= bootstrap_form_with model: @product do |f| %>
  <%= f.text_field :name %>
  <%= f.text_area :description %>
  <%= f.text_field :price, prepend: "$", inputmode: "decimal", pattern: "[0-9]*?(\\.[0-9]*)?" %>
  <%= f.text_field :quantity, inputmode: "numeric", pattern: "[1-9][0-9]*" %>
  <%= f.select :condition, Product.conditions.keys %>

  <%= f.collection_select :category_ids,
    Category.all, # selecting from all categories
    :id, :name, # the value submitted and the text shown
    { label: "Categories" },
    { multiple: true, required: true }
  %>

  <%# Preserve existing files when uploading new ones %>
  <% @product.photos.each do |photo| %>
    <%= f.hidden_field :photos, multiple: true, value: photo.identifier %>
  <% end %>
  <%= f.file_field :photos, multiple: true, accept: "image/*" %>

  <%= link_to "Cancel", :back, class: "btn btn-secondary" %>
  <%= f.primary %>
<% end %>

app/views/products/display.html.erb
<header>
  <h1>Product Page</h1>
  <!-- Navigation Bar -->
  <nav>
    <ul>
      <li><a href="#">Home</a></li>
      <li><a href="#">Products</a></li>
      <li><a href="#">Contact</a></li>
    </ul>
  </nav>
</header>

<%= bootstrap_form_with model: @user, url: signup_submit_path, method: :post, local: true do |f| %>
  <%= f.check_box :filter_1, label: 'Filter 1' %>
  <%= f.check_box :filter_2, label: 'Filter 2' %>
  <%= f.check_box :filter_3, label: 'Filter 3' %>
<% end %>

  <!-- Product Listings -->
  <div class="products" id="productListings">
    <!-- Product listings will be dynamically generated here -->
    <!-- Placeholder content -->
    <div class="product">
      <h3>Product 1</h3>
      <p>Description of Product 1</p>
      <p>$15.55</p>
    </div>
    <div class="product">
      <h3>Product 2</h3>
      <p>Description of Product 2</p>
      <p>$55.51</p>
    </div>
    <!-- End of placeholder content -->
  </div>

app/views/products/history.html.erb
<div class="container mt-4">
  <h2>Shopping history for <%= @user.first_name %></h2>
  <table class="table">
    <thead>
    <tr>
      <%# link_to defaults to the current URL when none is specified %>
      <th> </th>
      <th scope="col"><%= link_to 'Name', request.query_parameters.merge({:sort => 'name', :order => params[:order] == "desc"? "asc" : "desc", :category => params[:category], search: params[:search] }) %> </th>
      <th scope="col"><%= link_to 'Price', request.query_parameters.merge({ :sort => 'price', :order => params[:order] == "desc"? "asc" : "desc", :category => params[:category], search: params[:search] }) %> </th>
      <th scope="col"><%= link_to 'Posted', request.query_parameters.merge({ :sort => 'date', :order => params[:order] == "desc"? "asc" : "desc", :category => params[:category], search: params[:search] }) %> </th>
      <th scope="col"><%= link_to 'Views', request.query_parameters.merge({ :sort => 'views', :order => params[:order] == "desc"? "asc" : "desc", :category => params[:category], search: params[:search] }) %> </th>
    </tr>
    </thead>
    <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
          <div class="col-md-5 col-lg-4 float-md-start mb-3 me-md-3 me-lg-4 mt-2">
            <% photo_url = product.photos.first&.main&.url || "fallbacks/products/main_default.png" %>
            <%= image_tag photo_url, class: "img-fluid rounded border border-secondary-subtle" %>
          </div>
        </td>
        <td><%= link_to product.name, product_path(product.id) %></td>
        <td><%= number_to_currency product.price %></td>
        <td><%= product.created_at.strftime("%B %e, %Y %l:%M %p") %></td>
        <td><%= product.views %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/products/index.html.erb
<div class="container mt-4">
  <h2><%= products_index_header %></h2>
  <table class="table">
    <thead>
    <tr>
      <%# link_to defaults to the current URL when none is specified %>
      <th> </th>
      <th scope="col"><%= link_to 'Name', request.query_parameters.merge({:sort => 'name', :order => params[:order] == "desc"? "asc" : "desc", :category => params[:category], search: params[:search] }) %> </th>
      <th scope="col"><%= link_to 'Price', request.query_parameters.merge({ :sort => 'price', :order => params[:order] == "desc"? "asc" : "desc", :category => params[:category], search: params[:search] }) %> </th>
      <th scope="col"><%= link_to 'Posted', request.query_parameters.merge({ :sort => 'date', :order => params[:order] == "desc"? "asc" : "desc", :category => params[:category], search: params[:search] }) %> </th>
      <th scope="col"><%= link_to 'Views', request.query_parameters.merge({ :sort => 'views', :order => params[:order] == "desc"? "asc" : "desc", :category => params[:category], search: params[:search] }) %> </th>
    </tr>
    </thead>
    <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
          <div class="col-md-5 col-lg-4 float-md-start mb-3 me-md-3 me-lg-4 mt-2">
          <% photo_url = product.photos.first&.main&.url || "fallbacks/products/main_default.png" %>
          <%= image_tag photo_url, class: "img-fluid rounded border border-secondary-subtle" %>
          </div>
        </td>
        <td><%= link_to product.name, product_path(product.id) %></td>
        <td><%= number_to_currency product.price %></td>
        <td><%= product.created_at.strftime("%B %e, %Y %l:%M %p") %></td>
        <td><%= product.views %>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "form" %>

app/views/products/show.html.erb
<div class="clearfix mx-3">
  <div class="col-md-5 col-lg-4 float-md-start mb-3 me-md-3 me-lg-4 mt-2">
    <% photo_url = @product.photos.first&.main&.url || "fallbacks/products/main_default.png" %>
    <%= image_tag photo_url, class: "img-fluid rounded border border-secondary-subtle" %>
  </div>

  <div class="d-flex align-items-center justify-content-between">
    <h2 class="mb-1"><%= @product.name %></h2>
    <%= render "application/seller_dropdown", seller: @product.seller do %>
      <li>
        <%= link_to "Edit Product", edit_product_path(@product), class: "dropdown-item" %>
      </li>
    <% end %>
  </div>
  <%= render "products/listing/categories", product: @product %>
  <%= render "application/seller_info", seller: @seller, show_storefront: true %>
  <%= render "products/listing/price_alert", user: @user, product: @product if @user.present? %>
  <hr />

  <%= render "products/listing/condition", product: @product %>
  <%# We don't use bootstrap_form_with because we want to use custom styles %>
  <%= form_with url: add_to_cart_path do |form| %>
    <%= form.hidden_field :product_id, value: @product.id %>
    <%= render "products/listing/quantity_input", product: @product, form: form %>
    <%= render "products/listing/payment", product: @product, form: form %>
  <% end %>
</div>

<div class="mx-3">
  <h5 class="mb-2 mt-3">Product Description</h5>
  <p class="pre-wrap"><%= @product.description %></p>
</div>